//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAP_WSI.SQLaaSWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgReq", Namespace="https://SQLaaSWS")]
    [System.SerializableAttribute()]
    public partial class RgReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SqlVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassPhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReqTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RgId {
            get {
                return this.RgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RgIdField, value) != true)) {
                    this.RgIdField = value;
                    this.RaisePropertyChanged("RgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RgName {
            get {
                return this.RgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RgNameField, value) != true)) {
                    this.RgNameField = value;
                    this.RaisePropertyChanged("RgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zone {
            get {
                return this.ZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoneField, value) != true)) {
                    this.ZoneField = value;
                    this.RaisePropertyChanged("Zone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Avail {
            get {
                return this.AvailField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailField, value) != true)) {
                    this.AvailField = value;
                    this.RaisePropertyChanged("Avail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SqlVer {
            get {
                return this.SqlVerField;
            }
            set {
                if ((object.ReferenceEquals(this.SqlVerField, value) != true)) {
                    this.SqlVerField = value;
                    this.RaisePropertyChanged("SqlVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Dc {
            get {
                return this.DcField;
            }
            set {
                if ((object.ReferenceEquals(this.DcField, value) != true)) {
                    this.DcField = value;
                    this.RaisePropertyChanged("Dc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Env {
            get {
                return this.EnvField;
            }
            set {
                if ((object.ReferenceEquals(this.EnvField, value) != true)) {
                    this.EnvField = value;
                    this.RaisePropertyChanged("Env");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Tde {
            get {
                return this.TdeField;
            }
            set {
                if ((object.ReferenceEquals(this.TdeField, value) != true)) {
                    this.TdeField = value;
                    this.RaisePropertyChanged("Tde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SkuName {
            get {
                return this.SkuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuNameField, value) != true)) {
                    this.SkuNameField = value;
                    this.RaisePropertyChanged("SkuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string PassPhrase {
            get {
                return this.PassPhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.PassPhraseField, value) != true)) {
                    this.PassPhraseField = value;
                    this.RaisePropertyChanged("PassPhrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ReqTime {
            get {
                return this.ReqTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReqTimeField, value) != true)) {
                    this.ReqTimeField = value;
                    this.RaisePropertyChanged("ReqTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbReq", Namespace="https://SQLaaSWS")]
    [System.SerializableAttribute()]
    public partial class DbReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DbNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListenerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DboGrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwrGrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StdGrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AogNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RgId {
            get {
                return this.RgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RgIdField, value) != true)) {
                    this.RgIdField = value;
                    this.RaisePropertyChanged("RgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DbName {
            get {
                return this.DbNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DbNameField, value) != true)) {
                    this.DbNameField = value;
                    this.RaisePropertyChanged("DbName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Collation {
            get {
                return this.CollationField;
            }
            set {
                if ((object.ReferenceEquals(this.CollationField, value) != true)) {
                    this.CollationField = value;
                    this.RaisePropertyChanged("Collation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ListenerName {
            get {
                return this.ListenerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ListenerNameField, value) != true)) {
                    this.ListenerNameField = value;
                    this.RaisePropertyChanged("ListenerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DboGrp {
            get {
                return this.DboGrpField;
            }
            set {
                if ((object.ReferenceEquals(this.DboGrpField, value) != true)) {
                    this.DboGrpField = value;
                    this.RaisePropertyChanged("DboGrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PwrGrp {
            get {
                return this.PwrGrpField;
            }
            set {
                if ((object.ReferenceEquals(this.PwrGrpField, value) != true)) {
                    this.PwrGrpField = value;
                    this.RaisePropertyChanged("PwrGrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string StdGrp {
            get {
                return this.StdGrpField;
            }
            set {
                if ((object.ReferenceEquals(this.StdGrpField, value) != true)) {
                    this.StdGrpField = value;
                    this.RaisePropertyChanged("StdGrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AogName {
            get {
                return this.AogNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AogNameField, value) != true)) {
                    this.AogNameField = value;
                    this.RaisePropertyChanged("AogName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ConnectionString {
            get {
                return this.ConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true)) {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditEntry", Namespace="https://SQLaaSWS")]
    [System.SerializableAttribute()]
    public partial class AuditEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SQLVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialSizeMBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorPerfDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorPerfLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBoGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecoveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoggedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwrUGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StdUGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestITIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DC {
            get {
                return this.DCField;
            }
            set {
                if ((object.ReferenceEquals(this.DCField, value) != true)) {
                    this.DCField = value;
                    this.RaisePropertyChanged("DC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DBName {
            get {
                return this.DBNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DBNameField, value) != true)) {
                    this.DBNameField = value;
                    this.RaisePropertyChanged("DBName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SQLVer {
            get {
                return this.SQLVerField;
            }
            set {
                if ((object.ReferenceEquals(this.SQLVerField, value) != true)) {
                    this.SQLVerField = value;
                    this.RaisePropertyChanged("SQLVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string InitialSizeMB {
            get {
                return this.InitialSizeMBField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialSizeMBField, value) != true)) {
                    this.InitialSizeMBField = value;
                    this.RaisePropertyChanged("InitialSizeMB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Colation {
            get {
                return this.ColationField;
            }
            set {
                if ((object.ReferenceEquals(this.ColationField, value) != true)) {
                    this.ColationField = value;
                    this.RaisePropertyChanged("Colation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Network {
            get {
                return this.NetworkField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkField, value) != true)) {
                    this.NetworkField = value;
                    this.RaisePropertyChanged("Network");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Availability {
            get {
                return this.AvailabilityField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailabilityField, value) != true)) {
                    this.AvailabilityField = value;
                    this.RaisePropertyChanged("Availability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Zone {
            get {
                return this.ZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoneField, value) != true)) {
                    this.ZoneField = value;
                    this.RaisePropertyChanged("Zone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string StorPerfData {
            get {
                return this.StorPerfDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StorPerfDataField, value) != true)) {
                    this.StorPerfDataField = value;
                    this.RaisePropertyChanged("StorPerfData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string StorPerfLogs {
            get {
                return this.StorPerfLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.StorPerfLogsField, value) != true)) {
                    this.StorPerfLogsField = value;
                    this.RaisePropertyChanged("StorPerfLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Retention {
            get {
                return this.RetentionField;
            }
            set {
                if ((object.ReferenceEquals(this.RetentionField, value) != true)) {
                    this.RetentionField = value;
                    this.RaisePropertyChanged("Retention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string BUDI {
            get {
                return this.BUDIField;
            }
            set {
                if ((object.ReferenceEquals(this.BUDIField, value) != true)) {
                    this.BUDIField = value;
                    this.RaisePropertyChanged("BUDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DBoGroup {
            get {
                return this.DBoGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.DBoGroupField, value) != true)) {
                    this.DBoGroupField = value;
                    this.RaisePropertyChanged("DBoGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Recovery {
            get {
                return this.RecoveryField;
            }
            set {
                if ((object.ReferenceEquals(this.RecoveryField, value) != true)) {
                    this.RecoveryField = value;
                    this.RaisePropertyChanged("Recovery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string TDE {
            get {
                return this.TDEField;
            }
            set {
                if ((object.ReferenceEquals(this.TDEField, value) != true)) {
                    this.TDEField = value;
                    this.RaisePropertyChanged("TDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Logged {
            get {
                return this.LoggedField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggedField, value) != true)) {
                    this.LoggedField = value;
                    this.RaisePropertyChanged("Logged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Expire {
            get {
                return this.ExpireField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpireField, value) != true)) {
                    this.ExpireField = value;
                    this.RaisePropertyChanged("Expire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string PwrUGroup {
            get {
                return this.PwrUGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.PwrUGroupField, value) != true)) {
                    this.PwrUGroupField = value;
                    this.RaisePropertyChanged("PwrUGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string StdUGroup {
            get {
                return this.StdUGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.StdUGroupField, value) != true)) {
                    this.StdUGroupField = value;
                    this.RaisePropertyChanged("StdUGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string RequestITID {
            get {
                return this.RequestITIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestITIDField, value) != true)) {
                    this.RequestITIDField = value;
                    this.RaisePropertyChanged("RequestITID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://SQLaaSWS", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://SQLaaSWS", ConfigurationName="SQLaaSWS.SQLaaS_WSSoap")]
    public interface SQLaaS_WSSoap {
        
        // CODEGEN: Generating message contract since element name strRgName from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitNewRg", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.RitNewRgResponse RitNewRg(WAP_WSI.SQLaaSWS.RitNewRgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitNewRg", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitNewRgResponse> RitNewRgAsync(WAP_WSI.SQLaaSWS.RitNewRgRequest request);
        
        // CODEGEN: Generating message contract since element name strRgName from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitRgReqStatus", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.RitRgReqStatusResponse RitRgReqStatus(WAP_WSI.SQLaaSWS.RitRgReqStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitRgReqStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitRgReqStatusResponse> RitRgReqStatusAsync(WAP_WSI.SQLaaSWS.RitRgReqStatusRequest request);
        
        // CODEGEN: Generating message contract since element name strRgId from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitNewDb", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.RitNewDbResponse RitNewDb(WAP_WSI.SQLaaSWS.RitNewDbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitNewDb", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitNewDbResponse> RitNewDbAsync(WAP_WSI.SQLaaSWS.RitNewDbRequest request);
        
        // CODEGEN: Generating message contract since element name strDbName from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitDbReqStatus", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.RitDbReqStatusResponse RitDbReqStatus(WAP_WSI.SQLaaSWS.RitDbReqStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitDbReqStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitDbReqStatusResponse> RitDbReqStatusAsync(WAP_WSI.SQLaaSWS.RitDbReqStatusRequest request);
        
        // CODEGEN: Generating message contract since element name sDbName from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitEventStatus", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.RitEventStatusResponse RitEventStatus(WAP_WSI.SQLaaSWS.RitEventStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitEventStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitEventStatusResponse> RitEventStatusAsync(WAP_WSI.SQLaaSWS.RitEventStatusRequest request);
        
        // CODEGEN: Generating message contract since element name sField from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitGetValidPram", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.RitGetValidPramResponse RitGetValidPram(WAP_WSI.SQLaaSWS.RitGetValidPramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/RitGetValidPram", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitGetValidPramResponse> RitGetValidPramAsync(WAP_WSI.SQLaaSWS.RitGetValidPramRequest request);
        
        // CODEGEN: Generating message contract since element name strDBName from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/QueueDBDelete", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.QueueDBDeleteResponse QueueDBDelete(WAP_WSI.SQLaaSWS.QueueDBDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/QueueDBDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.QueueDBDeleteResponse> QueueDBDeleteAsync(WAP_WSI.SQLaaSWS.QueueDBDeleteRequest request);
        
        // CODEGEN: Generating message contract since element name GetVersionResult from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/GetVersion", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.GetVersionResponse GetVersion(WAP_WSI.SQLaaSWS.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.GetVersionResponse> GetVersionAsync(WAP_WSI.SQLaaSWS.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since element name whoamiResult from namespace https://SQLaaSWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/whoami", ReplyAction="*")]
        WAP_WSI.SQLaaSWS.whoamiResponse whoami(WAP_WSI.SQLaaSWS.whoamiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://SQLaaSWS/whoami", ReplyAction="*")]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.whoamiResponse> whoamiAsync(WAP_WSI.SQLaaSWS.whoamiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitNewRgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitNewRg", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitNewRgRequestBody Body;
        
        public RitNewRgRequest() {
        }
        
        public RitNewRgRequest(WAP_WSI.SQLaaSWS.RitNewRgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitNewRgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRgName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strZone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strAvail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strSqlVer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strDc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strEnv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strTde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strSkuName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strPassPhrase;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string strState;
        
        public RitNewRgRequestBody() {
        }
        
        public RitNewRgRequestBody(string strRgName, string strZone, string strAvail, string strSqlVer, string strDc, string strEnv, string strTde, string strSkuName, string strEmail, string strPassPhrase, string strState) {
            this.strRgName = strRgName;
            this.strZone = strZone;
            this.strAvail = strAvail;
            this.strSqlVer = strSqlVer;
            this.strDc = strDc;
            this.strEnv = strEnv;
            this.strTde = strTde;
            this.strSkuName = strSkuName;
            this.strEmail = strEmail;
            this.strPassPhrase = strPassPhrase;
            this.strState = strState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitNewRgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitNewRgResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitNewRgResponseBody Body;
        
        public RitNewRgResponse() {
        }
        
        public RitNewRgResponse(WAP_WSI.SQLaaSWS.RitNewRgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitNewRgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RitNewRgResult;
        
        public RitNewRgResponseBody() {
        }
        
        public RitNewRgResponseBody(string RitNewRgResult) {
            this.RitNewRgResult = RitNewRgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitRgReqStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitRgReqStatus", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitRgReqStatusRequestBody Body;
        
        public RitRgReqStatusRequest() {
        }
        
        public RitRgReqStatusRequest(WAP_WSI.SQLaaSWS.RitRgReqStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitRgReqStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRgName;
        
        public RitRgReqStatusRequestBody() {
        }
        
        public RitRgReqStatusRequestBody(string strRgName) {
            this.strRgName = strRgName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitRgReqStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitRgReqStatusResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitRgReqStatusResponseBody Body;
        
        public RitRgReqStatusResponse() {
        }
        
        public RitRgReqStatusResponse(WAP_WSI.SQLaaSWS.RitRgReqStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitRgReqStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WAP_WSI.SQLaaSWS.RgReq> RitRgReqStatusResult;
        
        public RitRgReqStatusResponseBody() {
        }
        
        public RitRgReqStatusResponseBody(System.Collections.Generic.List<WAP_WSI.SQLaaSWS.RgReq> RitRgReqStatusResult) {
            this.RitRgReqStatusResult = RitRgReqStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitNewDbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitNewDb", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitNewDbRequestBody Body;
        
        public RitNewDbRequest() {
        }
        
        public RitNewDbRequest(WAP_WSI.SQLaaSWS.RitNewDbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitNewDbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strRgId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strDbName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCollation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strDboGrp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strPwrGrp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strStdGrp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strState;
        
        public RitNewDbRequestBody() {
        }
        
        public RitNewDbRequestBody(string strRgId, string strDbName, string strCollation, string strDboGrp, string strPwrGrp, string strStdGrp, string strSize, string strState) {
            this.strRgId = strRgId;
            this.strDbName = strDbName;
            this.strCollation = strCollation;
            this.strDboGrp = strDboGrp;
            this.strPwrGrp = strPwrGrp;
            this.strStdGrp = strStdGrp;
            this.strSize = strSize;
            this.strState = strState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitNewDbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitNewDbResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitNewDbResponseBody Body;
        
        public RitNewDbResponse() {
        }
        
        public RitNewDbResponse(WAP_WSI.SQLaaSWS.RitNewDbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitNewDbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RitNewDbResult;
        
        public RitNewDbResponseBody() {
        }
        
        public RitNewDbResponseBody(string RitNewDbResult) {
            this.RitNewDbResult = RitNewDbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitDbReqStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitDbReqStatus", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitDbReqStatusRequestBody Body;
        
        public RitDbReqStatusRequest() {
        }
        
        public RitDbReqStatusRequest(WAP_WSI.SQLaaSWS.RitDbReqStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitDbReqStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strDbName;
        
        public RitDbReqStatusRequestBody() {
        }
        
        public RitDbReqStatusRequestBody(string strDbName) {
            this.strDbName = strDbName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitDbReqStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitDbReqStatusResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitDbReqStatusResponseBody Body;
        
        public RitDbReqStatusResponse() {
        }
        
        public RitDbReqStatusResponse(WAP_WSI.SQLaaSWS.RitDbReqStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitDbReqStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WAP_WSI.SQLaaSWS.DbReq> RitDbReqStatusResult;
        
        public RitDbReqStatusResponseBody() {
        }
        
        public RitDbReqStatusResponseBody(System.Collections.Generic.List<WAP_WSI.SQLaaSWS.DbReq> RitDbReqStatusResult) {
            this.RitDbReqStatusResult = RitDbReqStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitEventStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitEventStatus", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitEventStatusRequestBody Body;
        
        public RitEventStatusRequest() {
        }
        
        public RitEventStatusRequest(WAP_WSI.SQLaaSWS.RitEventStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitEventStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDbName;
        
        public RitEventStatusRequestBody() {
        }
        
        public RitEventStatusRequestBody(string sDbName) {
            this.sDbName = sDbName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitEventStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitEventStatusResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitEventStatusResponseBody Body;
        
        public RitEventStatusResponse() {
        }
        
        public RitEventStatusResponse(WAP_WSI.SQLaaSWS.RitEventStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitEventStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WAP_WSI.SQLaaSWS.AuditEntry> RitEventStatusResult;
        
        public RitEventStatusResponseBody() {
        }
        
        public RitEventStatusResponseBody(System.Collections.Generic.List<WAP_WSI.SQLaaSWS.AuditEntry> RitEventStatusResult) {
            this.RitEventStatusResult = RitEventStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitGetValidPramRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitGetValidPram", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitGetValidPramRequestBody Body;
        
        public RitGetValidPramRequest() {
        }
        
        public RitGetValidPramRequest(WAP_WSI.SQLaaSWS.RitGetValidPramRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitGetValidPramRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sField;
        
        public RitGetValidPramRequestBody() {
        }
        
        public RitGetValidPramRequestBody(string sField) {
            this.sField = sField;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RitGetValidPramResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RitGetValidPramResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.RitGetValidPramResponseBody Body;
        
        public RitGetValidPramResponse() {
        }
        
        public RitGetValidPramResponse(WAP_WSI.SQLaaSWS.RitGetValidPramResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class RitGetValidPramResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAP_WSI.SQLaaSWS.ArrayOfString RitGetValidPramResult;
        
        public RitGetValidPramResponseBody() {
        }
        
        public RitGetValidPramResponseBody(WAP_WSI.SQLaaSWS.ArrayOfString RitGetValidPramResult) {
            this.RitGetValidPramResult = RitGetValidPramResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueueDBDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueueDBDelete", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.QueueDBDeleteRequestBody Body;
        
        public QueueDBDeleteRequest() {
        }
        
        public QueueDBDeleteRequest(WAP_WSI.SQLaaSWS.QueueDBDeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class QueueDBDeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strDBName;
        
        public QueueDBDeleteRequestBody() {
        }
        
        public QueueDBDeleteRequestBody(string strDBName) {
            this.strDBName = strDBName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueueDBDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueueDBDeleteResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.QueueDBDeleteResponseBody Body;
        
        public QueueDBDeleteResponse() {
        }
        
        public QueueDBDeleteResponse(WAP_WSI.SQLaaSWS.QueueDBDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class QueueDBDeleteResponseBody {
        
        public QueueDBDeleteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(WAP_WSI.SQLaaSWS.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody {
        
        public GetVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(WAP_WSI.SQLaaSWS.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(string GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class whoamiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="whoami", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.whoamiRequestBody Body;
        
        public whoamiRequest() {
        }
        
        public whoamiRequest(WAP_WSI.SQLaaSWS.whoamiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class whoamiRequestBody {
        
        public whoamiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class whoamiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="whoamiResponse", Namespace="https://SQLaaSWS", Order=0)]
        public WAP_WSI.SQLaaSWS.whoamiResponseBody Body;
        
        public whoamiResponse() {
        }
        
        public whoamiResponse(WAP_WSI.SQLaaSWS.whoamiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://SQLaaSWS")]
    public partial class whoamiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string whoamiResult;
        
        public whoamiResponseBody() {
        }
        
        public whoamiResponseBody(string whoamiResult) {
            this.whoamiResult = whoamiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SQLaaS_WSSoapChannel : WAP_WSI.SQLaaSWS.SQLaaS_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQLaaS_WSSoapClient : System.ServiceModel.ClientBase<WAP_WSI.SQLaaSWS.SQLaaS_WSSoap>, WAP_WSI.SQLaaSWS.SQLaaS_WSSoap {
        
        public SQLaaS_WSSoapClient() {
        }
        
        public SQLaaS_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQLaaS_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLaaS_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLaaS_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.RitNewRgResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitNewRg(WAP_WSI.SQLaaSWS.RitNewRgRequest request) {
            return base.Channel.RitNewRg(request);
        }
        
        public string RitNewRg(string strRgName, string strZone, string strAvail, string strSqlVer, string strDc, string strEnv, string strTde, string strSkuName, string strEmail, string strPassPhrase, string strState) {
            WAP_WSI.SQLaaSWS.RitNewRgRequest inValue = new WAP_WSI.SQLaaSWS.RitNewRgRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitNewRgRequestBody();
            inValue.Body.strRgName = strRgName;
            inValue.Body.strZone = strZone;
            inValue.Body.strAvail = strAvail;
            inValue.Body.strSqlVer = strSqlVer;
            inValue.Body.strDc = strDc;
            inValue.Body.strEnv = strEnv;
            inValue.Body.strTde = strTde;
            inValue.Body.strSkuName = strSkuName;
            inValue.Body.strEmail = strEmail;
            inValue.Body.strPassPhrase = strPassPhrase;
            inValue.Body.strState = strState;
            WAP_WSI.SQLaaSWS.RitNewRgResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitNewRg(inValue);
            return retVal.Body.RitNewRgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitNewRgResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitNewRgAsync(WAP_WSI.SQLaaSWS.RitNewRgRequest request) {
            return base.Channel.RitNewRgAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitNewRgResponse> RitNewRgAsync(string strRgName, string strZone, string strAvail, string strSqlVer, string strDc, string strEnv, string strTde, string strSkuName, string strEmail, string strPassPhrase, string strState) {
            WAP_WSI.SQLaaSWS.RitNewRgRequest inValue = new WAP_WSI.SQLaaSWS.RitNewRgRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitNewRgRequestBody();
            inValue.Body.strRgName = strRgName;
            inValue.Body.strZone = strZone;
            inValue.Body.strAvail = strAvail;
            inValue.Body.strSqlVer = strSqlVer;
            inValue.Body.strDc = strDc;
            inValue.Body.strEnv = strEnv;
            inValue.Body.strTde = strTde;
            inValue.Body.strSkuName = strSkuName;
            inValue.Body.strEmail = strEmail;
            inValue.Body.strPassPhrase = strPassPhrase;
            inValue.Body.strState = strState;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitNewRgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.RitRgReqStatusResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitRgReqStatus(WAP_WSI.SQLaaSWS.RitRgReqStatusRequest request) {
            return base.Channel.RitRgReqStatus(request);
        }
        
        public System.Collections.Generic.List<WAP_WSI.SQLaaSWS.RgReq> RitRgReqStatus(string strRgName) {
            WAP_WSI.SQLaaSWS.RitRgReqStatusRequest inValue = new WAP_WSI.SQLaaSWS.RitRgReqStatusRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitRgReqStatusRequestBody();
            inValue.Body.strRgName = strRgName;
            WAP_WSI.SQLaaSWS.RitRgReqStatusResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitRgReqStatus(inValue);
            return retVal.Body.RitRgReqStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitRgReqStatusResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitRgReqStatusAsync(WAP_WSI.SQLaaSWS.RitRgReqStatusRequest request) {
            return base.Channel.RitRgReqStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitRgReqStatusResponse> RitRgReqStatusAsync(string strRgName) {
            WAP_WSI.SQLaaSWS.RitRgReqStatusRequest inValue = new WAP_WSI.SQLaaSWS.RitRgReqStatusRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitRgReqStatusRequestBody();
            inValue.Body.strRgName = strRgName;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitRgReqStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.RitNewDbResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitNewDb(WAP_WSI.SQLaaSWS.RitNewDbRequest request) {
            return base.Channel.RitNewDb(request);
        }
        
        public string RitNewDb(string strRgId, string strDbName, string strCollation, string strDboGrp, string strPwrGrp, string strStdGrp, string strSize, string strState) {
            WAP_WSI.SQLaaSWS.RitNewDbRequest inValue = new WAP_WSI.SQLaaSWS.RitNewDbRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitNewDbRequestBody();
            inValue.Body.strRgId = strRgId;
            inValue.Body.strDbName = strDbName;
            inValue.Body.strCollation = strCollation;
            inValue.Body.strDboGrp = strDboGrp;
            inValue.Body.strPwrGrp = strPwrGrp;
            inValue.Body.strStdGrp = strStdGrp;
            inValue.Body.strSize = strSize;
            inValue.Body.strState = strState;
            WAP_WSI.SQLaaSWS.RitNewDbResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitNewDb(inValue);
            return retVal.Body.RitNewDbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitNewDbResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitNewDbAsync(WAP_WSI.SQLaaSWS.RitNewDbRequest request) {
            return base.Channel.RitNewDbAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitNewDbResponse> RitNewDbAsync(string strRgId, string strDbName, string strCollation, string strDboGrp, string strPwrGrp, string strStdGrp, string strSize, string strState) {
            WAP_WSI.SQLaaSWS.RitNewDbRequest inValue = new WAP_WSI.SQLaaSWS.RitNewDbRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitNewDbRequestBody();
            inValue.Body.strRgId = strRgId;
            inValue.Body.strDbName = strDbName;
            inValue.Body.strCollation = strCollation;
            inValue.Body.strDboGrp = strDboGrp;
            inValue.Body.strPwrGrp = strPwrGrp;
            inValue.Body.strStdGrp = strStdGrp;
            inValue.Body.strSize = strSize;
            inValue.Body.strState = strState;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitNewDbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.RitDbReqStatusResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitDbReqStatus(WAP_WSI.SQLaaSWS.RitDbReqStatusRequest request) {
            return base.Channel.RitDbReqStatus(request);
        }
        
        public System.Collections.Generic.List<WAP_WSI.SQLaaSWS.DbReq> RitDbReqStatus(string strDbName) {
            WAP_WSI.SQLaaSWS.RitDbReqStatusRequest inValue = new WAP_WSI.SQLaaSWS.RitDbReqStatusRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitDbReqStatusRequestBody();
            inValue.Body.strDbName = strDbName;
            WAP_WSI.SQLaaSWS.RitDbReqStatusResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitDbReqStatus(inValue);
            return retVal.Body.RitDbReqStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitDbReqStatusResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitDbReqStatusAsync(WAP_WSI.SQLaaSWS.RitDbReqStatusRequest request) {
            return base.Channel.RitDbReqStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitDbReqStatusResponse> RitDbReqStatusAsync(string strDbName) {
            WAP_WSI.SQLaaSWS.RitDbReqStatusRequest inValue = new WAP_WSI.SQLaaSWS.RitDbReqStatusRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitDbReqStatusRequestBody();
            inValue.Body.strDbName = strDbName;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitDbReqStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.RitEventStatusResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitEventStatus(WAP_WSI.SQLaaSWS.RitEventStatusRequest request) {
            return base.Channel.RitEventStatus(request);
        }
        
        public System.Collections.Generic.List<WAP_WSI.SQLaaSWS.AuditEntry> RitEventStatus(string sDbName) {
            WAP_WSI.SQLaaSWS.RitEventStatusRequest inValue = new WAP_WSI.SQLaaSWS.RitEventStatusRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitEventStatusRequestBody();
            inValue.Body.sDbName = sDbName;
            WAP_WSI.SQLaaSWS.RitEventStatusResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitEventStatus(inValue);
            return retVal.Body.RitEventStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitEventStatusResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitEventStatusAsync(WAP_WSI.SQLaaSWS.RitEventStatusRequest request) {
            return base.Channel.RitEventStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitEventStatusResponse> RitEventStatusAsync(string sDbName) {
            WAP_WSI.SQLaaSWS.RitEventStatusRequest inValue = new WAP_WSI.SQLaaSWS.RitEventStatusRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitEventStatusRequestBody();
            inValue.Body.sDbName = sDbName;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitEventStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.RitGetValidPramResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitGetValidPram(WAP_WSI.SQLaaSWS.RitGetValidPramRequest request) {
            return base.Channel.RitGetValidPram(request);
        }
        
        public WAP_WSI.SQLaaSWS.ArrayOfString RitGetValidPram(string sField) {
            WAP_WSI.SQLaaSWS.RitGetValidPramRequest inValue = new WAP_WSI.SQLaaSWS.RitGetValidPramRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitGetValidPramRequestBody();
            inValue.Body.sField = sField;
            WAP_WSI.SQLaaSWS.RitGetValidPramResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitGetValidPram(inValue);
            return retVal.Body.RitGetValidPramResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitGetValidPramResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.RitGetValidPramAsync(WAP_WSI.SQLaaSWS.RitGetValidPramRequest request) {
            return base.Channel.RitGetValidPramAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.RitGetValidPramResponse> RitGetValidPramAsync(string sField) {
            WAP_WSI.SQLaaSWS.RitGetValidPramRequest inValue = new WAP_WSI.SQLaaSWS.RitGetValidPramRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.RitGetValidPramRequestBody();
            inValue.Body.sField = sField;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).RitGetValidPramAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.QueueDBDeleteResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.QueueDBDelete(WAP_WSI.SQLaaSWS.QueueDBDeleteRequest request) {
            return base.Channel.QueueDBDelete(request);
        }
        
        public void QueueDBDelete(string strDBName) {
            WAP_WSI.SQLaaSWS.QueueDBDeleteRequest inValue = new WAP_WSI.SQLaaSWS.QueueDBDeleteRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.QueueDBDeleteRequestBody();
            inValue.Body.strDBName = strDBName;
            WAP_WSI.SQLaaSWS.QueueDBDeleteResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).QueueDBDelete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.QueueDBDeleteResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.QueueDBDeleteAsync(WAP_WSI.SQLaaSWS.QueueDBDeleteRequest request) {
            return base.Channel.QueueDBDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.QueueDBDeleteResponse> QueueDBDeleteAsync(string strDBName) {
            WAP_WSI.SQLaaSWS.QueueDBDeleteRequest inValue = new WAP_WSI.SQLaaSWS.QueueDBDeleteRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.QueueDBDeleteRequestBody();
            inValue.Body.strDBName = strDBName;
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).QueueDBDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.GetVersionResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.GetVersion(WAP_WSI.SQLaaSWS.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion() {
            WAP_WSI.SQLaaSWS.GetVersionRequest inValue = new WAP_WSI.SQLaaSWS.GetVersionRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.GetVersionRequestBody();
            WAP_WSI.SQLaaSWS.GetVersionResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.GetVersionResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.GetVersionAsync(WAP_WSI.SQLaaSWS.GetVersionRequest request) {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.GetVersionResponse> GetVersionAsync() {
            WAP_WSI.SQLaaSWS.GetVersionRequest inValue = new WAP_WSI.SQLaaSWS.GetVersionRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.GetVersionRequestBody();
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAP_WSI.SQLaaSWS.whoamiResponse WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.whoami(WAP_WSI.SQLaaSWS.whoamiRequest request) {
            return base.Channel.whoami(request);
        }
        
        public string whoami() {
            WAP_WSI.SQLaaSWS.whoamiRequest inValue = new WAP_WSI.SQLaaSWS.whoamiRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.whoamiRequestBody();
            WAP_WSI.SQLaaSWS.whoamiResponse retVal = ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).whoami(inValue);
            return retVal.Body.whoamiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.whoamiResponse> WAP_WSI.SQLaaSWS.SQLaaS_WSSoap.whoamiAsync(WAP_WSI.SQLaaSWS.whoamiRequest request) {
            return base.Channel.whoamiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WAP_WSI.SQLaaSWS.whoamiResponse> whoamiAsync() {
            WAP_WSI.SQLaaSWS.whoamiRequest inValue = new WAP_WSI.SQLaaSWS.whoamiRequest();
            inValue.Body = new WAP_WSI.SQLaaSWS.whoamiRequestBody();
            return ((WAP_WSI.SQLaaSWS.SQLaaS_WSSoap)(this)).whoamiAsync(inValue);
        }
    }
}
