CREATE TABLE [dbo].[SKUSpecs]
(
	[SKUID] INT NOT NULL PRIMARY KEY, 
    [SKUNAME] VARCHAR(MAX) NOT NULL, 
    [SKUMEM] INT NOT NULL, 
    [SKUCORES] INT NOT NULL, 
    [SKUCHECKSUM] VARCHAR(MAX) NULL, 
    [SKUVISIBLE] INT NOT NULL
)
